# Generated by Django 4.2.2 on 2024-07-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_eth_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="eth_balance",
            field=models.FloatField(default=0.0),
        ),
    ]
